baseurl = "https://btcdca.info"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "BTC_DCA"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
enableGitInfo = true

[Params]
  subtitle = "Weekly Dollar Cost Averaging into Bitcoin"
  logo = "img/BTC_DCA_square_250.png"
  favicon = "img/favicon.ico"
  dateFormat = "2006 Jan 02"
  rss = true
  comments = true
  commit = "https://gitlab.com/thinkmassive/btc_dca/tree/"


#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Alex Miller"
  email = "alex@thinkmassive.org"
  gitlab = "thinkmassive/btc_dca"
  twitter = "thinkmassive"

[[menu.main]]
    name = "#StackSats Saturday"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.main]]
    identifier = "exchanges"
    name = "Exchanges"
    weight = 2

[[menu.main]]
    parent = "exchanges"
    name = "Swan"
    url = "exchange/swan"
    weight = 1

[[menu.main]]
    parent = "exchanges"
    name = "Casa"
    url = "exchange/casa"
    weight = 2

[[menu.main]]
    parent = "exchanges"
    name = "Fold"
    url = "exchange/fold"
    weight = 3

[[menu.main]]
    parent = "exchanges"
    name = "Square"
    url = "exchange/square"
    weight = 3

[[menu.main]]
    parent = "exchanges"
    name = "River"
    url = "exchange/river"
    weight = 3

